import { RestaurantType } from '@/types';

export const SAMPLE_RESTAURANTS: RestaurantType[] = [
  {
    id: 'resto_thies_01',
    name: 'Chez Fatou & Frères',
    tagline: 'Gastronomie sénégalaise authentique & Grillades au feu de bois',
    subdomain: 'chezfatou',
    ownerName: 'Fatou Diop & Modou Fall',
    phone: '+221 77 654 32 10',
    address: 'Avenue Léopold Sédar Senghor, Thiès, Sénégal',
    logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    currency: 'FCFA',
    isActive: true,
    tableCount: 12,
    tablesCount: 12,
    totalScans: 348,
    totalOrders: 174,
    totalRevenue: 642000,
    lastScanAt: '2026-08-26T19:40:00.000Z',
    lastOrderAt: '2026-08-26T19:35:00.000Z',
    createdAt: '2026-01-15T10:00:00.000Z',
    stats: {
      totalScans: 348,
      todayScans: 42,
      totalOrders: 174,
      totalRevenue: 642000,
      conversionRate: 50.0,
      averageBasket: 3689,
      peakHour: 13,
      peakHoursDistribution: [
        { hour: '11h', count: 14 },
        { hour: '12h', count: 48 },
        { hour: '13h', count: 86 },
        { hour: '14h', count: 52 },
        { hour: '15h', count: 18 },
        { hour: '19h', count: 32 },
        { hour: '20h', count: 64 },
        { hour: '21h', count: 45 },
        { hour: '22h', count: 21 },
      ],
      scansHistory30d: Array.from({ length: 30 }, (_, i) => ({
        date: `Jour ${i + 1}`,
        scans: 10 + Math.floor(Math.sin(i / 2) * 8 + i * 0.4 + Math.random() * 5),
      })),
      ordersHistory30d: Array.from({ length: 30 }, (_, i) => ({
        date: `Jour ${i + 1}`,
        orders: 5 + Math.floor(Math.sin(i / 2) * 4 + i * 0.2 + Math.random() * 3),
        revenue: (5 + Math.floor(Math.sin(i / 2) * 4 + i * 0.2 + Math.random() * 3)) * 3600,
      })),
      dailyHistory: [
        { day: 'Lun', scans: 38, orders: 18, revenue: 66000 },
        { day: 'Mar', scans: 34, orders: 17, revenue: 62500 },
        { day: 'Mer', scans: 42, orders: 21, revenue: 78000 },
        { day: 'Jeu', scans: 49, orders: 25, revenue: 92000 },
        { day: 'Ven', scans: 68, orders: 36, revenue: 134500 },
        { day: 'Sam', scans: 62, orders: 31, revenue: 118500 },
        { day: 'Dim', scans: 45, orders: 22, revenue: 84000 },
      ],
      scansByTable: [
        { tableNumber: 1, scans: 34 },
        { tableNumber: 2, scans: 28 },
        { tableNumber: 3, scans: 38 },
        { tableNumber: 4, scans: 52 },
        { tableNumber: 5, scans: 44 },
        { tableNumber: 6, scans: 26 },
        { tableNumber: 7, scans: 22 },
        { tableNumber: 8, scans: 20 },
        { tableNumber: 9, scans: 24 },
        { tableNumber: 10, scans: 18 },
        { tableNumber: 11, scans: 16 },
        { tableNumber: 12, scans: 15 },
      ],
    },
    subscription: {
      id: 'sub_01',
      plan: 'PRO',
      status: 'ACTIVE',
      price: 25000,
      startDate: '2026-01-15T00:00:00.000Z',
      endDate: '2026-10-15T23:59:59.000Z',
    },
    categories: [
      // 1. PLATS DU JOUR
      {
        id: 'cat_plats_du_jour',
        name: '⭐ Plats du jour',
        icon: '⭐',
        displayOrder: 0,
        items: [
          {
            id: 'dish_thieb_rouge',
            name: 'Ceebu Jën Pëndaa Mbaye (Riz Rouge)',
            nameWolof: 'Lou Ame Tay',
            wolofName: 'Ceebu Jën Bu Xonq',
            description: 'Riz rouge cuit au bouillon de mérou blanc frais, légumes du terroir (chou, manioc, carotte, beugueudj, tamarin).',
            price: 3500,
            imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: true,
            isSpecial: true,
            preparationTime: 10,
            rating: 4.9,
            allergens: ['Poisson', 'Crustacés'],
            categoryId: 'cat_plats_du_jour',
            spiceLevel: 2,
          },
          {
            id: 'dish_yassa_poulet',
            name: 'Yassa Poulet Fermier Braisé',
            nameWolof: 'Yassa Ginaar',
            wolofName: 'Yassa Ginaar',
            description: 'Cuisses de poulet marinées au citron vert de Casamance, oignons caramélisés et moutarde de Dijon, riz blanc.',
            price: 4000,
            imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: true,
            isSpecial: true,
            preparationTime: 12,
            rating: 4.8,
            allergens: ['Moutarde'],
            categoryId: 'cat_plats_du_jour',
            spiceLevel: 1,
          },
        ],
      },

      // 2. ENTRÉES
      {
        id: 'cat_entrees',
        name: '🥟 Entrées',
        icon: '🥟',
        displayOrder: 1,
        items: [
          {
            id: 'dish_pastels_thon',
            name: 'Portion de 10 Pastels au Thon',
            nameWolof: 'Pastels Jën',
            wolofName: 'Pastels Jën',
            description: 'Beignets dorés croustillants fourrés au thon épicé, accompagnés de notre fameuse sauce tomate aux oignons frits.',
            price: 2000,
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 8,
            rating: 4.7,
            allergens: ['Gluten', 'Poisson', 'Œufs'],
            categoryId: 'cat_entrees',
            spiceLevel: 1,
          },
          {
            id: 'dish_nems_poulet',
            name: 'Assiette de Nems Croustillants (x5)',
            nameWolof: 'Nems Ginaar',
            wolofName: 'Nems Ginaar',
            description: 'Nems roulés main, vermicelles, légumes croquants et poulet fermier, sauce aigre-douce et menthe.',
            price: 2500,
            imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 8,
            rating: 4.6,
            allergens: ['Gluten', 'Soja'],
            categoryId: 'cat_entrees',
            spiceLevel: 0,
          },
        ],
      },

      // 3. PLATS DE RÉSISTANCE
      {
        id: 'cat_plats_resistance',
        name: '🍲 Plats de résistance',
        icon: '🍲',
        displayOrder: 2,
        items: [
          {
            id: 'dish_dibi_agneau',
            name: 'Dibi d\'Agneau façon Thiès & Alloco',
            nameWolof: 'Dibi Xar',
            wolofName: 'Dibi Xar',
            description: 'Morceaux tendres d\'agneau marinés aux épices secrètes, grillés au feu de bois, oignons émincés piquants.',
            price: 5500,
            imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: true,
            isSpecial: true,
            preparationTime: 15,
            rating: 4.9,
            allergens: ['Moutarde'],
            categoryId: 'cat_plats_resistance',
            spiceLevel: 2,
          },
          {
            id: 'dish_mafe_boeuf',
            name: 'Mafé Kandja au Bœuf Fondant',
            nameWolof: 'Maffe Kandja',
            wolofName: 'Maffe Kandja',
            description: 'Sauce onctueuse à la pâte d\'arachide torréfiée, morceaux de bœuf braisé mijotés, gombos frais et patate douce.',
            price: 3500,
            imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: true,
            isSpecial: true,
            preparationTime: 10,
            rating: 4.8,
            allergens: ['Arachides'],
            categoryId: 'cat_plats_resistance',
            spiceLevel: 1,
          },
          {
            id: 'dish_capitaine_braise',
            name: 'Capitaine Entier Braisé & Alloco',
            nameWolof: 'Capitaine bu Ñor',
            wolofName: 'Capitaine Braisé',
            description: 'Capitaine frais de la Petite Côte braisé à la flamme, sauce pimentée aux herbes et bananes plantains frites.',
            price: 6500,
            imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 18,
            rating: 4.9,
            allergens: ['Poisson'],
            categoryId: 'cat_plats_resistance',
            spiceLevel: 2,
          },
          {
            id: 'dish_soupou_kandia',
            name: 'Soupou Kandja Royal aux Fruits de Mer',
            nameWolof: 'Soupou Kandia',
            wolofName: 'Soupou Kandia',
            description: 'Ragoût traditionnel au gombo frais et huile de palme rouge, crabe, crevettes, poisson fumé et bœuf tendre.',
            price: 4500,
            imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 15,
            rating: 4.7,
            allergens: ['Crustacés', 'Poisson', 'Mollusques'],
            categoryId: 'cat_plats_resistance',
            spiceLevel: 2,
          },
        ],
      },

      // 4. FASTFOOD
      {
        id: 'cat_fastfood',
        name: '🍔 Fastfood',
        icon: '🍔',
        displayOrder: 3,
        items: [
          {
            id: 'dish_burger_thies',
            name: 'Burger Gourmet Dakar & Frites',
            nameWolof: 'Burger Yàpp',
            wolofName: 'Burger Yàpp',
            description: 'Pain brioché artisanal, steak haché pur bœuf braisé minute, cheddar fondant, oignons caramélisés et sauce maison.',
            price: 3500,
            imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 10,
            rating: 4.8,
            allergens: ['Gluten', 'Lait', 'Moutarde'],
            categoryId: 'cat_fastfood',
            spiceLevel: 1,
          },
          {
            id: 'dish_chawarma_poulet',
            name: 'Chawarma Poulet Rôti Spécialité',
            nameWolof: 'Chawarma Ginaar',
            wolofName: 'Chawarma Ginaar',
            description: 'Galette libanaise toastée, émincé de poulet mariné aux épices, frites à l\'intérieur, cornichons et crème d\'ail.',
            price: 2500,
            imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 8,
            rating: 4.7,
            allergens: ['Gluten', 'Sésame'],
            categoryId: 'cat_fastfood',
            spiceLevel: 1,
          },
        ],
      },

      // 5. DESSERTS
      {
        id: 'cat_desserts',
        name: '🍨 Desserts',
        icon: '🍨',
        displayOrder: 4,
        items: [
          {
            id: 'dessert_thiakry',
            name: 'Thiakry / Dégué Gourmand',
            nameWolof: 'Caakiri',
            wolofName: 'Caakiri',
            description: 'Couscous de mil cuit à la vapeur, mélangé à un yaourt onctueux parfumé à la muscade, vanille et raisins secs.',
            price: 1500,
            imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 5,
            rating: 4.9,
            allergens: ['Lait', 'Gluten'],
            categoryId: 'cat_desserts',
            spiceLevel: 0,
          },
          {
            id: 'dessert_salade_fruits',
            name: 'Salade de Fruits Tropicaux',
            nameWolof: 'Salade de Fruits',
            wolofName: 'Salade de Fruits',
            description: 'Mangues Kent parfumées de Casamance, papaye fraîche et ananas au sirop de menthe.',
            price: 1500,
            imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 5,
            rating: 4.7,
            allergens: [],
            categoryId: 'cat_desserts',
            spiceLevel: 0,
          },
        ],
      },

      // 6. BOISSONS
      {
        id: 'cat_boissons',
        name: '🥤 Boissons',
        icon: '🥤',
        displayOrder: 5,
        items: [
          {
            id: 'drink_bissap_menthe',
            name: 'Jus de Bissap Rouge Frais (50cl)',
            nameWolof: 'Jus Bissap',
            wolofName: 'Jus Bissap',
            description: 'Infusion d\'hibiscus bio du Sénégal, feuilles de menthe fraîche et touche de fleur d\'oranger.',
            price: 1000,
            imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 3,
            rating: 4.9,
            allergens: [],
            categoryId: 'cat_boissons',
            spiceLevel: 0,
          },
          {
            id: 'drink_bouye_gingembre',
            name: 'Jus de Bouye Onctueux (Pain de Singe)',
            nameWolof: 'Jus Bouye',
            wolofName: 'Jus Bouye',
            description: 'Nectar crémeux extrait du fruit du baobab avec une pointe de lait concentré et vanille.',
            price: 1200,
            imageUrl: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 3,
            rating: 4.8,
            allergens: ['Lait'],
            categoryId: 'cat_boissons',
            spiceLevel: 0,
          },
        ],
      },
    ],
  },
];

export const SAMPLE_RESTAURANT = SAMPLE_RESTAURANTS[0];