import { RestaurantType } from '@/types';

export const SAMPLE_RESTAURANTS: RestaurantType[] = [
  // ----------------------------------------------------------------------------
  // 1. MG CAFÉ RESTO (Dakar) -> Pack STARTER
  // Login Commercial : demo.starter@louametay.sn / Demo123!
  // ----------------------------------------------------------------------------
  {
    id: 'tenant_mg_cafe_resto',
    name: 'MG Café Resto',
    tagline: 'Café Gourmand, Petit-Déjeuner & Grillades Express à Dakar',
    subdomain: 'mg-cafe-resto',
    ownerName: 'Moussa Guèye',
    phone: '+221 77 458 74 74',
    address: 'Plateau, Dakar, Sénégal',
    logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
    currency: 'FCFA',
    isActive: true,
    tableCount: 6,
    tablesCount: 6,
    totalScans: 148,
    totalOrders: 64,
    totalRevenue: 242000,
    lastScanAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    lastOrderAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    createdAt: '2026-01-15T10:00:00.000Z',
    subscription: {
      id: 'sub_mg_01',
      plan: 'STARTER',
      status: 'ACTIVE',
      price: 15000,
      startDate: '2026-01-15T00:00:00.000Z',
      endDate: '2027-01-15T23:59:59.000Z',
    },
    categories: [
      {
        id: 'cat_mg_dej',
        name: '🥐 Petit-Déjeuner',
        icon: '🥐',
        displayOrder: 1,
        items: [
          {
            id: 'item_mg_croque',
            name: 'Croque-Monsieur',
            wolofName: 'Croque-Monsieur',
            nameWolof: 'Croque-Monsieur',
            description: 'Pain toasté doré au beurre, garniture jambon de dinde et fromage fondant gratiné.',
            price: 1500,
            imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 8,
            rating: 4.8,
            allergens: ['Gluten', 'Lait'],
            categoryId: 'cat_mg_dej',
          },
          {
            id: 'item_mg_omelette',
            name: 'Omelette Espagnole',
            wolofName: 'Omelette Espagnole',
            nameWolof: 'Omelette Espagnole',
            description: 'Omelette généreuse aux pommes de terre fondantes et oignons doux.',
            price: 2000,
            imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 10,
            rating: 4.7,
            allergens: ['Œufs'],
            categoryId: 'cat_mg_dej',
          },
          {
            id: 'item_mg_cafe',
            name: 'Café au Lait',
            wolofName: 'Kafé ak Meew',
            nameWolof: 'Kafé ak Meew',
            description: 'Café richement torréfié mélangé à du lait chaud onctueux et mousseux.',
            price: 1500,
            imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 5,
            rating: 4.9,
            allergens: ['Lait'],
            categoryId: 'cat_mg_dej',
          },
        ],
      },
      {
        id: 'cat_mg_plats',
        name: '🍗 Plats',
        icon: '🍗',
        displayOrder: 2,
        items: [
          {
            id: 'item_mg_poulet',
            name: 'Poulet Entier Rôti aux Épices',
            wolofName: 'Ginaar bu Mbir',
            nameWolof: 'Ginaar bu Mbir',
            description: 'Poulet entier fermier rôti et assaisonné aux épices du terroir sénégalais.',
            price: 6500,
            imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: true,
            preparationTime: 20,
            rating: 5.0,
            allergens: ['Moutarde'],
            categoryId: 'cat_mg_plats',
          },
          {
            id: 'item_mg_dibi',
            name: 'Dibi Viande 500g',
            wolofName: 'Dibi Yàpp 500g',
            nameWolof: 'Dibi Yàpp 500g',
            description: '500g de viande de mouton braisée au feu de bois avec moutarde, oignons et piment.',
            price: 4000,
            imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 18,
            rating: 4.8,
            allergens: ['Moutarde'],
            categoryId: 'cat_mg_plats',
          },
          {
            id: 'item_mg_thiof',
            name: 'Thiof Grillé & Alloco',
            wolofName: 'Coof bu Ñor',
            nameWolof: 'Coof bu Ñor',
            description: 'Mérou blanc Thiof frais grillé à la braise avec alloco doré et sauce verte.',
            price: 4500,
            imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 18,
            rating: 4.9,
            allergens: ['Poisson'],
            categoryId: 'cat_mg_plats',
          },
        ],
      },
      {
        id: 'cat_mg_fast',
        name: '🌯 Fast-food',
        icon: '🌯',
        displayOrder: 3,
        items: [
          {
            id: 'item_mg_tacos',
            name: 'Tacos Viande Hachée',
            wolofName: 'Tacos Yàpp',
            nameWolof: 'Tacos Yàpp',
            description: 'Tacos français garni de viande hachée assaisonnée, frites croustillantes et sauce fromagère.',
            price: 2500,
            imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 10,
            rating: 4.7,
            allergens: ['Gluten', 'Lait'],
            categoryId: 'cat_mg_fast',
          },
        ],
      },
    ],
  },

  // ----------------------------------------------------------------------------
  // 2. CHEZ COLLÉ RESTAURANT (Thiès) -> Pack PRO
  // Login Commercial : demo.pro@louametay.sn / Demo123!
  // ----------------------------------------------------------------------------
  {
    id: 'tenant_chez_colle',
    name: 'Chez Collé Restaurant',
    tagline: 'Saveurs Thiessoises Authentiques, Grillades au Feu de Bois & Pizzas',
    subdomain: 'chez-colle',
    ownerName: 'Collé Cissé',
    phone: '+221 77 458 74 74',
    address: 'Avenue Lamine Guèye, Thiès, Sénégal',
    logoUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    currency: 'FCFA',
    isActive: true,
    tableCount: 14,
    tablesCount: 14,
    totalScans: 486,
    totalOrders: 242,
    totalRevenue: 890000,
    lastScanAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    lastOrderAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    createdAt: '2026-01-20T10:00:00.000Z',
    subscription: {
      id: 'sub_colle_01',
      plan: 'PRO',
      status: 'ACTIVE',
      price: 25000,
      startDate: '2026-01-20T00:00:00.000Z',
      endDate: '2027-01-20T23:59:59.000Z',
    },
    categories: [
      {
        id: 'cat_colle_entrees',
        name: '🥗 Entrées',
        icon: '🥗',
        displayOrder: 1,
        items: [
          {
            id: 'item_colle_nicoise',
            name: 'Salade Niçoise',
            description: 'Salade fraîcheur au thon blanc, œufs durs, olives noires, haricots verts et pommes de terre.',
            price: 3500,
            imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 8,
            rating: 4.8,
            allergens: ['Poisson', 'Œufs'],
            categoryId: 'cat_colle_entrees',
          },
        ],
      },
      {
        id: 'cat_colle_viandes',
        name: '🥩 Viandes',
        icon: '🥩',
        displayOrder: 2,
        items: [
          {
            id: 'item_colle_cotedeboeuf',
            name: 'Côte de Bœuf Grillée',
            description: 'Pièce noble de bœuf sélectionné grillée à point, servie avec frites maison et sauce au poivre vert.',
            price: 6000,
            imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: true,
            preparationTime: 18,
            rating: 4.9,
            allergens: ['Lait'],
            categoryId: 'cat_colle_viandes',
          },
          {
            id: 'item_colle_dibi',
            name: 'Dibi 1Kg Traditionnel',
            description: 'Dibi d\'agneau braisé au feu de bois selon la pure tradition thiessoise, oignons et piment doux.',
            price: 7000,
            imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 18,
            rating: 4.9,
            allergens: ['Moutarde'],
            categoryId: 'cat_colle_viandes',
          },
        ],
      },
      {
        id: 'cat_colle_pizzas',
        name: '🍕 Pizzas',
        icon: '🍕',
        displayOrder: 3,
        items: [
          {
            id: 'item_colle_reine',
            name: 'Pizza Reine',
            description: 'Sauce tomate mijotée, mozzarella fondante, jambon blanc et champignons frais.',
            price: 4500,
            imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 12,
            rating: 4.7,
            allergens: ['Gluten', 'Lait'],
            categoryId: 'cat_colle_pizzas',
          },
          {
            id: 'item_colle_margherita',
            name: 'Pizza Margherita',
            description: 'Sauce tomate maison aux herbes, mozzarella fior di latte, basilic frais et filet d\'huile d\'olive.',
            price: 4000,
            imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 12,
            rating: 4.8,
            allergens: ['Gluten', 'Lait'],
            categoryId: 'cat_colle_pizzas',
          },
        ],
      },
      {
        id: 'cat_colle_burgers',
        name: '🍔 Burgers',
        icon: '🍔',
        displayOrder: 4,
        items: [
          {
            id: 'item_colle_simple',
            name: 'Burger Simple',
            description: 'Burger classique avec steak pur bœuf grillé minute, salade, tomate, oignon et sauce burger.',
            price: 1300,
            imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 10,
            rating: 4.6,
            allergens: ['Gluten', 'Moutarde'],
            categoryId: 'cat_colle_burgers',
          },
          {
            id: 'item_colle_cheese',
            name: 'Cheese Burger Fondant',
            description: 'Burger gourmand avec steak pur bœuf, tranche de fromage cheddar fondu, salade et sauce onctueuse.',
            price: 1500,
            imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 10,
            rating: 4.8,
            allergens: ['Gluten', 'Lait', 'Moutarde'],
            categoryId: 'cat_colle_burgers',
          },
        ],
      },
      {
        id: 'cat_colle_pates',
        name: '🍝 Pâtes',
        icon: '🍝',
        displayOrder: 5,
        items: [
          {
            id: 'item_colle_spagh',
            name: 'Spaghetti Bolognaise Pur Bœuf',
            description: 'Spaghetti al dente nappés d\'une sauce bolognaise maison à la viande pur bœuf et parmesan.',
            price: 4000,
            imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281072?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 10,
            rating: 4.8,
            allergens: ['Gluten', 'Lait'],
            categoryId: 'cat_colle_pates',
          },
        ],
      },
    ],
  },

  // ----------------------------------------------------------------------------
  // 3. HÔTEL RESTAURANT CAYOR (Saly / Mbour) -> Pack PREMIUM (Multi-Zones & 5 Langues)
  // Login Commercial : demo.premium@louametay.sn / Demo123!
  // ----------------------------------------------------------------------------
  {
    id: 'tenant_hotel_cayor',
    name: 'Hôtel Restaurant Cayor',
    tagline: 'Complexe Hôtelier & Gastronomique • Multi-Zones & Carte Internationale',
    subdomain: 'hotel-cayor',
    ownerName: 'Direction Hôtel Cayor',
    phone: '+221 77 458 74 74',
    address: 'Zone Balnéaire, Saly Portudal / Mbour, Sénégal',
    logoUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=300&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
    currency: 'FCFA',
    isActive: true,
    tableCount: 24,
    tablesCount: 24,
    totalScans: 1140,
    totalOrders: 560,
    totalRevenue: 3450000,
    lastScanAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    lastOrderAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    createdAt: '2026-02-01T10:00:00.000Z',
    subscription: {
      id: 'sub_cayor_01',
      plan: 'PREMIUM',
      status: 'ACTIVE',
      price: 45000,
      startDate: '2026-02-01T00:00:00.000Z',
      endDate: '2027-02-01T23:59:59.000Z',
    },
    categories: [
      {
        id: 'cat_cayor_entrees',
        name: '🥗 Entrées',
        icon: '🥗',
        displayOrder: 1,
        items: [
          {
            id: 'item_cayor_cesar',
            name: 'Salade César au Poulet Fermier',
            description: 'Cœur de romaine, aiguillettes de poulet grillé, croûtons dorés à l\'ail, copeaux de parmesan AOP et sauce César.',
            price: 4500,
            imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 10,
            rating: 4.9,
            allergens: ['Gluten', 'Lait', 'Œufs'],
            categoryId: 'cat_cayor_entrees',
          },
        ],
      },
      {
        id: 'cat_cayor_viandes',
        name: '🥩 Viandes',
        icon: '🥩',
        displayOrder: 2,
        items: [
          {
            id: 'item_cayor_filet',
            name: 'Filet de Bœuf Rôti au Beurre',
            description: 'Filet de bœuf tendre rôti au beurre clarifié, réduction au jus corsé, écrasé de pommes de terre et légumes glacés.',
            price: 6000,
            imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 18,
            rating: 5.0,
            allergens: ['Lait'],
            categoryId: 'cat_cayor_viandes',
          },
        ],
      },
      {
        id: 'cat_cayor_poissons',
        name: '🐟 Poissons',
        icon: '🐟',
        displayOrder: 3,
        items: [
          {
            id: 'item_cayor_thiof',
            name: 'Thiof Grillé Royal & Alloco',
            description: 'Mérou blanc de ligne braisé à la plancha, marinade aux herbes du Sine Saloum, riz blanc parfumé et alloco.',
            price: 6000,
            imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 20,
            rating: 4.9,
            allergens: ['Poisson'],
            categoryId: 'cat_cayor_poissons',
          },
        ],
      },
      {
        id: 'cat_cayor_pizzas',
        name: '🍕 Pizzas Signature',
        icon: '🍕',
        displayOrder: 4,
        items: [
          {
            id: 'item_cayor_burrata',
            name: 'Pizza Burrata Gourmet',
            description: 'Pizza d\'exception avec une boule entière de Burrata crémeuse d\'Italie, tomates confites, roquette et pesto basilic.',
            price: 9000,
            imageUrl: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 12,
            rating: 5.0,
            allergens: ['Gluten', 'Lait'],
            categoryId: 'cat_cayor_pizzas',
          },
          {
            id: 'item_cayor_dibi',
            name: 'Pizza Dibi au Feu de Bois',
            description: 'Création fusion : base crème, mozzarella, lamelles de dibi d\'agneau mariné au feu de bois, oignons rouges et piment doux.',
            price: 7000,
            imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: true,
            preparationTime: 12,
            rating: 5.0,
            allergens: ['Gluten', 'Lait'],
            categoryId: 'cat_cayor_pizzas',
          },
        ],
      },
      {
        id: 'cat_cayor_desserts',
        name: '🍰 Desserts',
        icon: '🍰',
        displayOrder: 5,
        items: [
          {
            id: 'item_cayor_tiramisu',
            name: 'Tiramisu Maison',
            description: 'Véritable tiramisu italien maison aux biscuits imbibés au café expresso, crème mascarpone et cacao amer.',
            price: 3000,
            imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 5,
            rating: 4.9,
            allergens: ['Lait', 'Œufs', 'Gluten'],
            categoryId: 'cat_cayor_desserts',
          },
        ],
      },
      {
        id: 'cat_cayor_boissons',
        name: '🥤 Boissons',
        icon: '🥤',
        displayOrder: 6,
        items: [
          {
            id: 'item_cayor_jus',
            name: 'Jus Locaux Frais (Bissap, Bouye, Gingembre)',
            description: 'Assortiment de purs jus artisanaux de saison : Bissap mentholé, Bouye au lait ou Gingembre tonique.',
            price: 1500,
            imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
            isAvailable: true,
            isSpecialOfTheDay: false,
            preparationTime: 3,
            rating: 4.9,
            allergens: [],
            categoryId: 'cat_cayor_boissons',
          },
        ],
      },
    ],
  },
];

export const SAMPLE_RESTAURANT = SAMPLE_RESTAURANTS[0];